name: Backend Start Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: [ main ]
    
jobs:
  test-start:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
      
    - name: Install dependencies
      working-directory: backend
      run: npm ci
      
    - name: Test Backend Startup
      working-directory: backend
      run: |
        # Create a timeout to kill the server after 30 seconds (assuming successful start)
        timeout 30s npm start || EXIT_CODE=$?
        
        # Exit code 124 from timeout means the command was terminated after running the specified time
        # which means our server started and kept running (good outcome)
        if [ $EXIT_CODE -eq 124 ]; then
          echo "Server stayed up for 30 seconds"
          exit 0
        else
          echo "Server failed or crashed"
          exit 1
        fi
      env:
        PORT: ${{ secrets.PORT }}
        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
        STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        STRAVA_REDIRECT_URI: ${{ secrets.STRAVA_REDIRECT_URI }}
        CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        SVIX_API_URL: ${{ secrets.SVIX_API_URL }}
