name: Cypress E2E Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest

    env:
      # Frontend env vars
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
      VITE_STRAVA_CLIENT_ID: ${{ secrets.VITE_STRAVA_CLIENT_ID }}
      VITE_STRAVA_REDIRECT_URI: ${{ secrets.VITE_STRAVA_REDIRECT_URI }}
      VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}

      # Backend env vars
      PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
      STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      STRAVA_REDIRECT_URI: ${{ secrets.STRAVA_REDIRECT_URI }}
      CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      SVIX_API_URL: ${{ secrets.SVIX_API_URL }}
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Create Cypress fixtures directory
        run: |
          mkdir -p frontend/cypress/fixtures/test-data
          mkdir -p frontend/cypress/downloads

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Start backend server
        working-directory: ./backend
        run: npm start &

      - name: Start frontend server
        working-directory: ./frontend
        run: npm run dev &

      - name: Wait for frontend to be ready
        run: |
          echo "Waiting for frontend to be ready..."
          timeout 60 bash -c 'until curl -s http://localhost:5173 > /dev/null; do sleep 1; done'
          echo "Frontend is up!"

      - name: Run Cypress tests
        working-directory: ./frontend
        run: npm run test:e2e
        env:
          CYPRESS_baseUrl: http://localhost:5173

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: frontend/cypress/videos
          if-no-files-found: ignore
